### ISSUE TITLE
add java modulation system into project

### ISSUE THREAD

**Issue by quimodotcom** [sonallux/spotify-web-api-java#59]
add java modulation system into project

**Comment by sonallux** [comment]
> add java modulation system into project

I think you mean the Java module system, do you?

Since I have no problems without the Java module system, I have not added support for it yet. But nevertheless, it seems reasonable to add the corresponding `module-info.java` to the project.

@quimodotcom do you want to provide a PR for it? Otherwise, I am going to do it in the next weeks.

**Comment by quimodotcom** [comment]
I don't really need to provide an pr. but thank you so much! would mean the world if you could do this!

**Comment by quimodotcom** [comment]
Any update???

**Comment by sonallux** [comment]
@quimodotcom Sorry for the delay, I have been busy with other projects.

But I can finally provide a beta version with a `module-info`. You can check out the changes in draft PR #66 . I have also released a beta version `2.2.0-beta.0` containing the changes of the PR. It might take a while till the published beta release is available on maven central.

Currently, a multi-release jar file is created. This means that the `module-info` is under `META-INF/versions/11` inside the jar file. I do not know if a multi-release jar file is really required. Alternatively, a normal jar file with the `module-info` in the root directory of the jar file can also be used. It would be cool if you could provide any guidance on which option is better or prefered. 

Could you please test the beta version and provide feedback.
